services:
  app:
    # image: kadmap-calendar:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3035:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
            - dist/
            - .next/
            - .git/
            - .vscode/
            - .idea/
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=fluid
      - POSTGRES_PASSWORD=fluid
      - POSTGRES_DB=fluid_calendar
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fluid -d fluid_calendar"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    # ports:
    #   - "5432:5432"  # Expose PostgreSQL port

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=dracula

volumes:
  postgres_dev_data:
