services:
  app:
    image: kadmap-calendar:latest
    ports:
      - "3035:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=fluid
      - POSTGRES_PASSWORD=fluid
      - POSTGRES_DB=fluid_calendar
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fluid -d fluid_calendar"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_dev_data:
